# Javascript Node CircleCI 2.0 configuration file
# This is atest
# Review me - https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-create.html
#
# https://github.com/jacquesfu/aws-eb-cli-cheatsheet
#   
# eb init my-project-name --region us-east-1 -k awsSupport-USG --profile eb-cli -p python-2.7 -k awsSupport-USG

#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

        environment:
          ## this enables colors in the output
          TERM: xterm

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run:
          name: Install awscli
          command: |
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade

      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[default]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
            echo "aws_session_token=$AWS_SESSION_TOKEN" >> ~/.aws/config
            echo "region=$region" >> ~/.aws/config

      - run:
          name: Deploy to EB if branch is Master
          command: |
            eb init --region us-east-1 --platform MyNodeJSApp appname -k awsSupport-USG -p Node.js
            eb create dev-env
            #eb use circleci-beanstalk-example --profile eb-cli --region us-east-1
            #eb deploy -v --staged --profile eb-cli
